version: '2'
services:
  postgresql:
    extends:
      file: postgresql.yaml
      service: postgresql
    container_name: postgresql
  minio:
    extends:
      file: minio.yml
      service: minio
    container_name: minio